Email Integration For CSSA and enhancement for DERA email functionality
bcgov/nr-epd-digital-services pull request #542
Opened 2023-10-10 23:17 UTC by midhun-aot

# Description

Please provide a summary of the change and the issue fixed. Please include relevant context. List dependency changes.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

## Further comments

2023-10-11 18:50 UTC, nikhila-aot requested changes

2023-10-11 20:33 UTC, midhun-aot commented on forms-flow-ai/forms-flow-ai-ee/forms-flow-bpm/templates/request_updated.ftl
> +                <span id="nom_notification" style="overflow: visible;line-height: 30px;text-align: left;font-style: normal;font-weight: bold;font-size: 20px;color: rgba(0, 51, 102, 1);letter-spacing:
done

2023-10-11 20:35 UTC, midhun-aot commented on forms-flow-ai/forms-flow-ai-ee/forms-flow-bpm/processes/Bundling/subProcess/CSSABundleWorklow.bpmn
> +task.execution.setVariable('userRole','Case Worker');</camunda:script>
done

2023-10-11 20:35 UTC, midhun-aot commented on forms-flow-ai/forms-flow-ai-ee/forms-flow-bpm/processes/Bundling/subProcess/CSSABundleWorklow.bpmn
> +task.execution.setVariable('subFormName','DERA Form');</camunda:script>
fixed

2023-10-11 20:35 UTC, midhun-aot commented on forms-flow-ai/forms-flow-ai-ee/forms-flow-bpm/processes/Bundling/subProcess/CSSABundleWorklow.bpmn
> +task.execution.setVariable('subFormName','DERA Form');
fixed

2023-10-12 17:35 UTC, nikhila-aot approved these changes

2023-10-12 17:35 UTC, merged