API to assign 'formsflow-client' group to BCSC and BCeID users
bcgov/nr-epd-digital-services pull request #656
Opened 2024-04-03 23:32 UTC by jaspalsingh-aot

# Description

Please provide a summary of the change and the issue fixed. Please include relevant context. List dependency changes.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

## Further comments

2024-04-05 17:43 UTC, nikhila-aot requested changes

2024-04-05 18:14 UTC, jaspalsingh-aot commented on backend/users/src/app/services/KeycloakService.service.ts
> +          const group = this.findGroupIdByName(response.data, groupName);
implemented method is faster.

2024-04-05 20:58 UTC, jaspalsingh-aot commented on backend/users/src/app/controllers/users.controller.ts
> +export class UsersController {
Changed to UserController and User.controller.ts

2024-04-05 20:59 UTC, jaspalsingh-aot commented on backend/users/src/app/services/KeycloakService.service.ts
> +export class KeycloakService {
changed as suggested.

2024-04-05 20:59 UTC, jaspalsingh-aot commented on backend/users/src/app/controllers/users.controller.ts
> +@Unprotected()
working on it.

2024-04-09 17:19 UTC, nikhila-aot approved these changes

2024-04-09 17:20 UTC, merged