Site Input Text Search Initial Checkin
bcgov/nr-epd-digital-services pull request #659
Opened 2024-04-09 05:32 UTC by midhun-aot

# Description

Please provide a summary of the change and the issue fixed. Please include relevant context. List dependency changes.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

## Further comments

2024-04-11 16:49 UTC, nikhila-aot requested changes

2024-04-11 16:49 UTC, nikhila-aot commented on frontend/Site/src/declaration.d.ts
> +declare module '*.png';
remove if not needed

2024-04-11 16:49 UTC, nikhila-aot commented on frontend/Site/src/utilities/test/TestUtils.tsx
> +    // }
remove commented code

2024-04-16 22:04 UTC, midhun-aot commented on frontend/Site/src/app/components/navigation/Footer.tsx
> +              The B.C. Public Service acknowledges the territories of First Nations around B.C. and is grateful to carry out our work on these lands. We acknowledge the rights, interests, priorities,
This will modified / removed later

2024-04-16 22:20 UTC, midhun-aot commented on frontend/Site/src/declaration.d.ts
> +declare module '*.png';
required

2024-05-30 04:53 UTC, nikhila-aot approved these changes

2024-05-30 04:54 UTC, merged